<a href="https://colab.research.google.com/github/sakshii009/MLT-colab-pracctice/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1-D array
import numpy as np
arr = np.array([1,2,3,4])
print(arr*2)
print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [5]:
# 2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
# 3-D array
import numpy as np
arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)
print(type(arr))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
<class 'numpy.ndarray'>


In [22]:
import pandas as pd
dataset = {
    'Subject' : ['MLT','BDA','CC','ANN'],
    'Marks' : ['80','85','90','95']
}
data = pd.DataFrame(dataset)

print(data)

  Subject Marks
0     MLT    80
1     BDA    85
2      CC    90
3     ANN    95
